Allow expired billing teams to be deleted
FlowFuse/flowfuse pull request #3187
Opened 2023-12-08 11:41 UTC by hardillb

part of #2559

## Description

Allow a team with expired billing e.g. at end of trial to be deleted even if it has instances/applications.

## Related Issue(s)

#2559 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2023-12-08 11:41 UTC, hardillb commented
Need to work out some tests for this

2023-12-08 11:56 UTC, hardillb commented
Change to Billing.vue is just wrapping the whole thing in a `<div>` to clear VSCode lint warning

2023-12-08 18:26 UTC, hardillb commented
The failing testcase is not something I've touched.

Wonder if it's a race condition?

2023-12-11 15:16 UTC, knolleary commented on forge/routes/api/team.js
> +                // It is possible the team has Instances but expired billing so
We need to delete devices as well.

2023-12-11 15:24 UTC, hardillb commented on forge/routes/api/team.js
> +                // It is possible the team has Instances but expired billing so
Yep, will add that

2023-12-13 13:39 UTC, knolleary commented on forge/routes/api/team.js
> +                    // disconnect any devices from the Instance
Given we're about to delete the devices, I don't think we should send them all a command that will cause them to call home and change their state.

2023-12-13 13:40 UTC, knolleary requested changes
One more tweak needed - no need to send devices a command if we're about to delete them anyway.

2023-12-14 11:15 UTC, knolleary approved these changes

2023-12-14 11:16 UTC, merged