User Identification via HubSpot Integration
FlowFuse/flowfuse pull request #3407
Opened 2024-01-30 09:49 UTC by Yndira-FlowForge

## Description

Enabled HubSpot
Added the user identification script according to https://developers.hubspot.com/docs/api/events/tracking-code#identify-a-visitor

## Related Issue(s)

closes [#3392](https://github.com/FlowFuse/flowfuse/issues/3392)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-01-30 09:55 UTC, Yndira-FlowForge commented
Hi @knolleary 
I've added a script to enable HubSpot's survey and chat features, as well as to identify visitors. To identify the visitors, I'm fetching the user's email and sending it to HubSpot. I wanted to check with you if this is the best approach. Is there a need to fetch the user's email like this, or is it already available through another method?

2024-01-30 13:23 UTC, knolleary requested changes

2024-01-30 13:23 UTC, knolleary commented on etc/flowforge.yml
We don't need to add this to the default yml file - particular our own tracking code.

2024-01-30 13:23 UTC, knolleary commented on forge/routes/ui/index.js
I think we should be doing this in the Vue code of the application - as that will already have identified the current logged-in user and have the information available and avoids the need for this duplicate API call.

That will need a bit more work as we don't currently pass the hubspot config over to the Vue code... but I have an idea. I'll pick this up if you'd like.

2024-01-30 13:29 UTC, Yndira-FlowForge commented on forge/routes/ui/index.js
Thank you @knolleary

> I'll pick this up if you'd like.

Yes, please, I haven't worked with Vue before 🙃

2024-02-02 17:35 UTC, knolleary commented
Closing this PR as it will be superseded by #3411

2024-02-02 17:35 UTC, closed without merging