Improve scalability of device editor
FlowFuse/flowfuse pull request #3511
Opened 2024-02-22 17:11 UTC by knolleary

This updates the Device Editor tunnel handling to make it scalable.

Closes:
 - #2514 
 - #3367 

# Summary of changes

 - Adds news fields to the Device model to store editor tunnel state:
    - `editorToken` - the access token to be used. Unlike other tokens, this has to be stored in the clear as it needs to be retrievable to give to both the device and frontend when someone tries to access the editor
    - `editorAffinity` - if set, this is the value of the `FFSESSION` affinity cookie the device has been given by the `ingress-nginx` load balancer. This allows us to set a matching cookie on any api request for this device's details.
    - `editorConnected` - whether the editor tunnel is currently connected or not

 - Adds a new `local` property to the device editor status object. This is a boolean flag that indicates if the device agent websocket is connected to the instance that is servicing the api request.

The key logic is all around the `editorAffinity` property and the `FFSESSION` cookie.

When a user enables the Device Editor, the device agent will connect to the platform and the ingress will give it a cookie to ensure affinity with a particular upstream platform instance. The Device Agent communicates the value of that cookie back to the platform (both in response to the MQTT command to enable the editor, *and* as part of its regular status checkin).

The load balancer is configured to set the path of the `FFSESSION` cookie to `/api/v1/device` (because we cannot do wildcard locations in the nginx config).

Any api request to `/api/v1/device/<hashid>` will get its own `FFSESSION` cookie set to match that of the device (if the device is connected). This means subsequent rquests from the client should hit the *same* instance the device is connected to.

### Older Device Agent support

Older device agents do not know about the affinity cookie - they will connect without the cookie and end up wherever the load balancer puts them.

To try to cater for that, the `local` property on the device editor status object is used. If the frontend wants to connect to the device it can check the `local` property. If its false, it knows it is not talking to the instance that holds the connection. But in making that request, the server will also notice the same thing and attempt to set/clear the FFSESSION cookie. The frontend can then retry - hopefully to get load balanced to a different instance. We optimistically hope it will eventually get load-balanced to the right instance (it tries 10 times before stopping.. the user can retry themselves).

### Current unknowns

All of this logic relies on specific behaviours of `ingress-nginx` around its affinity cookies. I have been testing against a local setup with a home-brew load balancer that mimics the understood behaviour of ingress-nginx. Now its time to put this behind a real instance to see if the behaviour matches what I think it will be.

We also have to test different browsers as various StackOverflow posts imply different behaviours around multiple same-named cookies.

### Remaining work

 - Get this branch built and deployed into the scalability test environment
 - Update the unit tests for some of the API changes I've made - I've not looked at them yet as we need to verify the concept works first.

2024-02-22 21:25 UTC, hardillb commented
I have built versions of the containers and stored them in my container repo, we should be able to pull them in the morning.

Will review code first thing

2024-02-26 09:28 UTC, hardillb requested changes
First pass looks good

I've flagged all the console.log/console.warns

2024-02-26 09:28 UTC, hardillb commented on forge/routes/api/device.js
> +        app.log.info(`NOL: Clearing top-level FFSESSION cookie for device ${request.device.hashid}`)
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on forge/routes/api/device.js
> +            app.log.info('NOL: Clearing FFSESSION cookie on generic path')
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on forge/routes/api/device.js
> +                        app.log.info(`NOL: Setting FFSESSION cookies to known affinity for device ${request.device.hashid} : ${request.device.editorAffinity}`)
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on forge/routes/api/device.js
> +                        app.log.info(`NOL: Clearing FFSESSION cookies as we don't have affinity for device ${request.device.hashid}`)
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on frontend/src/pages/device/index.vue
> +                console.warn(`openTunnel launchEditor:${launchEditor} ${JSON.stringify(this.device.editor)}`)
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on frontend/src/pages/device/index.vue
> +                        console.warn(' - open editor')
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on frontend/src/pages/device/index.vue
> +                        console.warn(' - show dialog')
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on frontend/src/pages/device/index.vue
> +                            console.warn(' - pollTunnelStatus', attempt, timeout)
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on frontend/src/pages/device/index.vue
> +                                    console.warn(` - poll result ${JSON.stringify(this.device.editor)}`)
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on frontend/src/pages/device/index.vue
> +                                                console.warn(' - open editor')
```suggestion
```

2024-02-26 09:28 UTC, hardillb commented on frontend/src/pages/device/index.vue
> +                                console.warn(' - enabling editor tunnel')
```suggestion
```

2024-02-27 17:39 UTC, knolleary commented
Unit tests passing. Final task is to tidy up the Device Editor buttons on the new home screen. Choice is to either get the buttons working, or hide them for now.

Will time-box an hour tomorrow on getting the buttons working, otherwise will hide them and move forward.

2024-02-29 10:37 UTC, knolleary commented
This is now ready for full review.

2024-03-01 10:12 UTC, hardillb approved these changes
I've given it another read through and it looks good.

2024-03-08 09:51 UTC, knolleary commented
Okay - I think this is good to merge. Will do further validation on staging as well.

2024-03-08 09:51 UTC, merged