Add new immersive instance editor
FlowFuse/flowfuse pull request #3709
Opened 2024-04-10 10:17 UTC by sherbastian

## Description

- Added a new Plain layout and slightly refactored the routing layout selection
- Added a new immersive instance editor page & styling using the existing instance routes
- Added the ability for FF frontend app to communicate with the embedded editor iframe via post messages 
- Extracted common alert, dialog and instance functionality into separate mixins in order to be shared across layouts and pages
- Added the ff-colors stylesheet as a global webpack import to have access to color variables across vue templates without explicit imports

## Related Issue(s)

closes[ #3656](https://github.com/FlowFuse/flowfuse/issues/3656)
depends on 
- [#224](https://github.com/FlowFuse/nr-launcher/pull/224) 
- [#3740](https://github.com/FlowFuse/flowfuse/pull/3740) 
- [#3732](https://github.com/FlowFuse/flowfuse/pull/3732)
- [PR #229](https://github.com/FlowFuse/nr-launcher/pull/229)

part of https://github.com/FlowFuse/flowfuse/issues/3646

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-04-16 08:49 UTC, joepavitt commented
Let's break this into multiple PRs:

- Webpack config for shared `scss` files
- "Plain" layout and dynamic setting of that layout in `meta`
- ... the rest of it

2024-04-16 14:39 UTC, sherbastian commented
The PR is broken and tests will fail untill [3740](https://github.com/FlowFuse/flowfuse/pull/3740) and [3732](https://github.com/FlowFuse/flowfuse/pull/3732) are merged into main

2024-04-18 07:55 UTC, sherbastian commented
merged everything together and seems to be ok! Made one adjustment based on @Yndira-E's proposal (open the drawer with a delay when accessing the immersive editor to make it clear that it's interactive ) and added the full wordmark logo as the drawer trigger (it got lost in a draft variation)

2024-04-18 11:17 UTC, joepavitt requested changes
Mostly looks great, only thing noticed (which is what i think is causing the E2E test failures) is that the routing has changed from `/instance` to `/project` - Already spoken with @sherbastian though and this is getting fixed imminently.

2024-04-18 12:05 UTC, joepavitt commented
good @sherbastian do we need nr-launcher updates published/merged first I assume in order for this to run?

2024-04-18 12:22 UTC, joepavitt commented
Okay, so NR Launcher first (after https://github.com/FlowFuse/nr-launcher/pull/229), then we can merge this with the updated dependency

2024-04-18 12:23 UTC, knolleary commented
Can I assume this all works okay *without* the nr-launcher update? We cannot force users to update their instances to pickup any nr-launcher changes, so this needs to fall back cleanly

2024-04-18 14:16 UTC, sherbastian commented on frontend/src/pages/instance/Editor/components/EditorWrapper.vue
> +            title="YouTube video player"
it should be removed, it's a leftover since it was an embedded youtube iframe in it's inception

2024-04-18 14:17 UTC, sherbastian commented on frontend/src/pages/instance/Editor/components/EditorWrapper.vue
> +        window.addEventListener('message', this.eventListener)
yes

2024-04-18 14:18 UTC, joepavitt commented on frontend/src/pages/instance/Editor/components/EditorWrapper.vue
> +            title="YouTube video player"
Please remove it - it's still in the PR currently

2024-04-18 15:17 UTC, joepavitt commented
Now just awaiting E2E's before this can be merged

2024-04-18 15:24 UTC, sherbastian commented
yes, working on them!

2024-04-19 07:44 UTC, sherbastian commented
Should be GTG!

2024-04-19 13:06 UTC, joepavitt approved these changes
Congrats on the approval & merge of your first FlowFuse PR @sherbastian 👏

2024-04-19 13:06 UTC, merged