Allow user setting node red version setting for application assigned devices
FlowFuse/flowfuse pull request #3766
Opened 2024-04-23 18:05 UTC by Steve-Mcl

**NOTE: Part 1 of 2. Only merge when both this and the device agent counterpart are both approved.**

## Description

As per [Approach](https://github.com/FlowFuse/flowfuse/issues/2802#issuecomment-2071738509) in issue discussion:

> 1. Add `editor` side tab to device->settings
> 2. Get/Set an object `editor` in `DeviceSettings` Table
>    1. this provides a place for future editor based settings
> 3. Override the starter & actual snapshots `.modules['node-red']` version if `editor.nodeRedVersion` is set
>    1. This acts like an override of any snapshot applied to the device
>    2. Clearing the value reverts to using the version in the snapshot (latest for starter/whatever was stack was used for the snapshot)

further details and considerations are written in the linked issue

## Related Issue(s)

#2802

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-04-24 12:17 UTC, Steve-Mcl commented
Arrrrgggghhhh

unrelated e2e test still failing

```
  1) FlowForge - Team Overview (Home) - With License
       shows a list of cloud hosted instances:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'application-device-a' within the element: <li> but never did.
      at Context.eval (webpack:///../test/e2e/frontend/cypress/tests-ee/team/overview.spec.js:123:27)
```

Tests run cleanly in local env with cypress open. will try full run without cypress open locally - perhaps something related to other tests is causing order of elements to be different?

2024-05-01 15:43 UTC, knolleary requested changes
As this has some dependency on the agent version, I think we should inform the user what behaviour they will get based on the known agent version.

 - older agents: NR version will only get applied when a new snapshot is deployed
 - new agents: NR version will get updated after settings saved (and/or new snapshot is deployed).

Exactly what version number to test for depends on us releasing the Device Agent - which we can do first

2024-05-01 15:49 UTC, Steve-Mcl commented
> Exactly what version number to test for depends on us releasing the Device Agent - which we can do first
> * older agents: NR version will only get applied when a new snapshot is deployed
> * new agents: NR version will get updated after settings saved (and/or new snapshot is deployed).



@Steve-Mcl 
_For the personal memory banks - reminder to follow up once new release of device agent is cut_

Add feedback when user applies a NR version to the device - so that they know when/how the set version will be applied (based on the agent version)

2024-05-02 11:56 UTC, Steve-Mcl commented
Since Agent is currently v2.4.0 and xxx has been merged, i can use a semvar <= 2.4.0 to indicate the alternative meeans of applying the NR version update.

Here is a demo - lay out was discussed with @joepavitt 


![chrome_WiS2CuKSuS](https://github.com/FlowFuse/flowfuse/assets/44235289/b403f906-d711-42ba-b146-aa535f73bf33)


Footnotes:

| agent version | footnote |
| --------: | :-------- |
| <= 2.4.0 | The device will be updated to the specified version when a different snapshot is deployed |
| > 2.4.0 | The device will be updated to the specified version and restarted upon saving the settings |

2024-05-03 08:23 UTC, knolleary commented on frontend/src/pages/device/Settings/Editor.vue
> +                return 'The device will be updated to the specified version when a different snapshot is deployed'
```suggestion
                return 'The device will be updated to the specified version the next time a snapshot is deployed'
```

Slight rewording suggestion

2024-05-03 08:24 UTC, knolleary approved these changes
Approved - with just one small rewording suggestion

2024-05-03 09:52 UTC, knolleary commented
Only pause is now that this setting *doesn't* get applied if the device is in developer mode. Lets move forward with this for now, but I think we need a step back look at developer mode and how we communicate what does/doesn't happen whilst in that state and how we can improve things. For example, we don't let a pipeline stage get triggered from a developer-mode device.... which feels odd if its your development device you want to snapshot and deploy... but I digress and will follow up separately.

2024-05-03 12:46 UTC, merged