4184 Add notifications drawer
FlowFuse/flowfuse pull request #4210
Opened 2024-07-18 16:28 UTC by cstns

## Description

Adds a notifications drawer boilerplate. Currently only supports team invitations but is easily extended to future notifications

## Related Issue(s)
closes https://github.com/FlowFuse/flowfuse/issues/4184

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-07-18 17:21 UTC, joepavitt requested changes
- Odd glitch on close where it seems to span the full width for a brief millisecond or two, then pull back?

https://github.com/user-attachments/assets/a6082067-0bcd-4ce3-bd85-6237dd8007d9

- I'd also expect to be able to click the notifications icon _again_ to close too, not just have to click into empty space.
- We should also change the red of the `ff-notification-pill` to `#d12c2b` as it's too dark at the moment
- We also need to improve the padding and vertical alignment of the notifications themselves:

<img width="402" alt="Screenshot 2024-07-18 at 18 20 49" src="https://github.com/user-attachments/assets/64783431-15a5-4509-a594-adf2740e7e8a">

I'm happy to do that myself though if you don't mind handling the other recommendations

2024-07-18 17:21 UTC, joepavitt commented on frontend/src/components/NotificationsButton.vue
> +    padding: 10px;
```suggestion
    padding: 18px;
```

2024-07-18 17:21 UTC, joepavitt commented on frontend/src/components/NotificationsButton.vue
> +      height: 35px;
```suggestion
      width: 24px;
      height: 24px;
```

2024-07-18 17:23 UTC, joepavitt commented
As an FYI too, we have `ff-icon`, `ff-icon-lg` and `ff-icon-sm` which you can use here too. The icon in the notification itself for example can just use `ff-icon ff-icon-lg` and it'll then be 24px squared.

2024-07-18 17:24 UTC, cstns commented
I'm looking into the collapse bug! Feel free to make any adjustments you feel necessary!

2024-07-19 11:37 UTC, joepavitt commented
Made some structural improvmenets by having all of the structure live inside a `Notification.vue` component with relevant slots that the bespoke notifications can extend.

I've also then modified the CSS slightly to implement the following changes:

### Before

<img width="847" alt="Screenshot 2024-07-19 at 12 36 54" src="https://github.com/user-attachments/assets/660792d2-5d3a-4cfa-aed6-f04a857c4fe7">

### After

<img width="772" alt="Screenshot 2024-07-19 at 12 34 07" src="https://github.com/user-attachments/assets/014696c3-d5bd-4e43-80c8-9512745c64ff">

2024-07-19 11:41 UTC, joepavitt commented
Waiting for tests to run - but will approve once they're successful

2024-07-19 12:52 UTC, joepavitt approved these changes

2024-07-19 12:52 UTC, merged