Product Tour - Welcome to FlowFuse
FlowFuse/flowfuse pull request #4383
Opened 2024-08-15 14:38 UTC by joepavitt

## Description

- Add infrastructrue to render interactive product tours
   - ShepherdJS to run the tour logic
   - VueX store to track state on whether we should be showing tour or now
- Adds the first "welcome" tour
   - Set to active if user arrives via the verify e-mail screen

## Related Issue(s)

Closes #2721 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass

2024-08-15 14:40 UTC, joepavitt commented
Example PH Funnel to track progress:

<img width="1303" alt="Screenshot 2024-08-15 at 15 39 45" src="https://github.com/user-attachments/assets/39314815-ec10-40d5-b9d4-1ecac9f56849">

2024-08-15 15:32 UTC, Steve-Mcl reviewed
Should we not be conditioning the tour or adapting to what is present in the team?

Also, is this intended for FFC or FFD also? 
Because while we do auto create an application and instance, FFD might not 🤷  

As an example, a user joining an existing team and signing in for the first time, when they access the existing team that has no instances or does have devices - it throws off the dialog.

![image](https://github.com/user-attachments/assets/0e9c4422-c221-42bf-9ab8-4dc2f0deca95)

![image](https://github.com/user-attachments/assets/816a39ad-c575-4cd0-a4be-5dfb8d6c145c)

2024-08-15 19:22 UTC, joepavitt commented
Great point re: dedicated and joining existing teams... I'll adjust it accordingly. May need to be conditional (not sure how yet) on that last "Open Editor" step.

2024-08-16 12:28 UTC, joepavitt commented on frontend/src/tours/tour-welcome.json
@gstout52 FYI - tour script is here if you want to review. @Steve-Mcl made great points that we need to make this host agnostic, so this covers all hosting options quite nicely, and even for new users coming into an existing team, full of resources.

2024-08-16 12:47 UTC, Steve-Mcl approved these changes
Agnostic language reads better. I feel this can support varying setups.

2024-08-16 12:50 UTC, gstout52 requested changes
Looks great! Two very small things:

Devices is currently:
<p><b>Devices</b> are Node-RED instances that are managed and deployed <i>remotely</i>.</p><p>Whether hardware in factories or a Raspberry Pi on your desk. FlowFuse helps you manage hundreds of remote deployments.</p>

I recommend combining the last two sentences: <p><b>Devices</b> are Node-RED instances that are managed and deployed <i>remotely</i>.</p><p>Whether hardware in factories or a Raspberry Pi on your desk, FlowFuse helps you manage hundreds of remote deployments.</p>

Open editor is currently:
<p><b>That's our quick introduction to FlowFuse</b></p><p>When you're ready, we recommend you open a Node-RED editor and start building your first flow.</p>

I recommend this slight change in language:
<p><b>That's our quick introduction to FlowFuse</b></p><p>When you're ready, we recommend that you open a Node-RED editor and start building your first flow.</p>

2024-08-16 12:53 UTC, joepavitt commented on frontend/src/tours/tour-welcome.json
> +    "text": "<p><b>Devices</b> are Node-RED instances that are managed and deployed <i>remotely</i>.</p><p>Whether hardware in factories or a Raspberry Pi on your desk. FlowFuse helps you manage hund
```suggestion
    "text": "<p><b>Devices</b> are Node-RED instances that are managed and deployed <i>remotely</i>.</p><p>Whether hardware in factories or a Raspberry Pi on your desk, FlowFuse helps you manage hundreds of remote deployments.</p>",
```

2024-08-16 12:54 UTC, gstout52 commented on frontend/src/tours/tour-welcome.json
> +    "text": "<p><b>That's our quick introduction to FlowFuse</b></p><p>When you're ready, we recommend you open a Node-RED editor and start building your first flow.</p>",
```suggestion
    "text": "<p><b>That's our quick introduction to FlowFuse.</b></p><p>When you're ready, we recommend that you open a Node-RED editor and start building your first flow.</p>",
```

2024-08-16 13:44 UTC, gstout52 approved these changes

2024-08-16 13:44 UTC, merged