4381 invites posthog
FlowFuse/flowfuse pull request #4386
Opened 2024-08-15 19:19 UTC by joepavitt

## Description

- Registers a new "product" service for the `app`
- Adds `posthog-node` as a new dependency
- Wraps the `capture` function for PostHog, which is initiated using the same `config` as the frontend

### Todo

- Unit tests?
- Wire the product service into the accepting of team invites server-side

## Related Issue(s)

Closes #4381 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass

2024-08-16 14:20 UTC, joepavitt commented
Have a working end-to-end:

<img width="1426" alt="Screenshot 2024-08-16 at 15 20 36" src="https://github.com/user-attachments/assets/9796c392-4923-4096-94ef-2aa7e2518958">

2024-08-16 15:16 UTC, Steve-Mcl reviewed
looks good to me Joe but in the spirit of "done" there are no tests.

I think at minimum we should have unit tests that checks `app.product.capture` is a function. Better still would be to perform an invite, spy `app.notifications.send` and check the arguments in the call are sane (no raw `id`s)

2024-08-16 16:00 UTC, joepavitt commented
Yep, haven't touched the server-side unit tests before, so wasn't sure how deep to go with it.

2024-08-16 16:02 UTC, joepavitt commented
Not sure why the `notifications.send` is picked up in the diff, as that should be on `main` already

2024-08-20 15:54 UTC, joepavitt commented
@Steve-Mcl I've updated the branch now so that the diff _doesn't_ include all the stuff from https://github.com/FlowFuse/flowfuse/pull/4385/files too

2024-08-27 08:02 UTC, Steve-Mcl requested changes

2024-08-27 08:02 UTC, Steve-Mcl commented on package.json
> +        "posthog-node": "^4.1.0",
there was a guard for null values added in 4.1.1.  also V4.2.0 is released.

We should probably switch to 4.1.1 at min.

2024-08-27 13:28 UTC, Steve-Mcl approved these changes
good to go

2024-08-27 13:28 UTC, merged