Add static asset service user docs
FlowFuse/flowfuse pull request #4426
Opened 2024-08-29 16:40 UTC by cstns

## Description

Add static asset service user docs

## Related Issue(s)

none

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-08-30 12:51 UTC, joepavitt commented
Any reason for the draft? Or can I review?

2024-08-30 12:55 UTC, cstns commented
There's an open question on dpt eng about some points in the docs that would need clarifying

2024-08-30 12:55 UTC, cstns commented
about the limitations section*

2024-09-02 12:35 UTC, hardillb commented
@cstns how are we doing with this?

2024-09-02 12:41 UTC, cstns commented
I need to update the limitations section. 
I have an answer for Unsupported characters, which ill make a vague remark about depending on file system, but the other two remain unanswered:
	- Allowed MIME types: // todo couldn't find any on the BE or localfs driver
	- Team permissions required: owner // to be confirmed or rephrased

2024-09-02 12:43 UTC, hardillb commented
We do not care about mime types for the currently deployed code, everything is just uploaded as binary blob.

We may want to think about mime types for when sharing is enabled, but that is part of the next release (and we are going to default to what Node-RED already does).

2024-09-02 12:48 UTC, hardillb commented
Only Owner and Members should be able to access the Assests tab.

2024-09-02 12:59 UTC, cstns commented
As we stand, viewer type roles have access to the assets tab, but cannot retrieve assets so the list is always empty. The asset action buttons are still enabled (refresh, new folder and upload).

Should I create another issue or do a quick fix in this one?

I can also remove the mime type restriction from the docs until we implement it.

2024-09-02 13:00 UTC, hardillb commented
Raise an issue for the Viewer stuff.

Remove the mime stuff

2024-09-02 13:11 UTC, cstns commented
linking https://github.com/FlowFuse/flowfuse/issues/4439

2024-09-02 13:20 UTC, hardillb requested changes
Also probably need a link from docs/users/index.md in the "Working with Files and Context" section

2024-09-02 13:20 UTC, hardillb commented on docs/user/static-asset-service.md
> +Our platform now includes a Static Asset Service, enabling you to save, access, and manage files seamlessly within your hosted Node-RED instances.
```suggestion
Our platform now includes a Static Asset Service, enabling you to manage files seamlessly within your hosted Node-RED instances.
```

Removing access and leaving it as just manage for now.

2024-09-02 13:20 UTC, hardillb commented on docs/user/static-asset-service.md
> +- A launcher version of 2.8.0 or greater.
```suggestion
- A Instance Stack with a launcher version of 2.8.0 or greater.
```

2024-09-02 14:27 UTC, hardillb commented
Raised follow up https://github.com/FlowFuse/flowfuse/issues/4440 to clean up file node docs.

2024-09-02 14:27 UTC, hardillb approved these changes

2024-09-02 14:28 UTC, merged