Team broker client UI
FlowFuse/flowfuse pull request #4646
Opened 2024-10-15 13:48 UTC by hardillb

fixes https://github.com/FlowFuse/flowfuse/issues/4433
## Description

Starts to add the UI for adding Broker Clients

Still needs a lot of work

#1350 

## Related Issue(s)

https://github.com/FlowFuse/flowfuse/issues/4433

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-10-15 15:34 UTC, hardillb commented
@joepavitt this is functional enough for me to test things, but needs a lot of love.

I also need to write the backend API for edits to the ACL and to allow password changes. Will get those done tomorrow.

2024-10-15 15:35 UTC, joepavitt commented
@cstns how you looking on Visual History? Need me to jump in here, or could you finish both, visual history _and_ this by Thursday next week?

2024-10-16 06:36 UTC, cstns commented
I think I could tackle both! My best guess is that the Visual History ui will be done by the end on this week and can jump to this one afterwards.

2024-10-16 09:22 UTC, hardillb commented
Couple of points

- create/edit/delete should only be available to team owner
- dashboard only users should not have access

2024-10-16 12:27 UTC, hardillb commented
Also when displaying the username, it should have `@[teamHashId]` added to the end.

e.g. is username `alice`  is created in a team with a hash id of `1234abc` then the username should be displayed as `alice@1234abc`

Might be worth adding another dialog shown after creating a user that shows the username (and client id with the same value) and the topics.

2024-10-22 15:53 UTC, hardillb commented
Quick note from testing latest checked in code.

- The Create client button need to only be available to Team Owners
- Likewise delete option when implemented

2024-10-23 07:30 UTC, cstns commented
@Yndira-E, please give us a hand with the empty state icon and broker pictograms! 

I created https://github.com/FlowFuse/flowfuse/issues/4680

2024-10-23 10:48 UTC, hardillb commented
Editing a client is not populating the existing rules into the dialog

![image](https://github.com/user-attachments/assets/dd28d90f-17e1-4334-8c4f-a2ac5491929d)


![image](https://github.com/user-attachments/assets/f172453b-9251-4e5d-a1cc-f31370161ada)

2024-10-23 10:54 UTC, hardillb commented
~~Sorry to drop this on you so late, but how hard would it be to add an extra column? called client id and shows the same as the username?~~

Actually scratch that, can we change the username field to had the header "Username/ClientId"

2024-10-23 11:01 UTC, hardillb reviewed
I've flagged a few things

2024-10-23 11:01 UTC, hardillb commented on frontend/src/pages/team/Library/TeamLibrary.vue
> +        <div v-if="isSharedLibraryFeatureEnabled" class="breadcrumbs-wrapper">
I assume this is a fix for something you spotted while working on this?

2024-10-23 12:24 UTC, hardillb commented
We should be able to remove all, just not the last one.

As it is we can never remove the first rule.

![Uploading image.png…]()

2024-10-23 12:50 UTC, hardillb commented on frontend/src/pages/team/Broker/index.vue
> +                                <span class="username">Username</span>
```suggestion
                                <span class="username">Username/ClientId</span>
```

2024-10-23 13:19 UTC, cstns commented
> We should be able to remove all, just not the last one.
> 
> As it is we can never remove the first rule.
> 
> ![Screenshot from 2024-10-23 13-24-22](https://private-user-images.githubusercontent.com/1800845/379265103-97c2906c-e2f7-412b-875a-ef10b0d6ae56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODk3NTcsIm5iZiI6MTcyOTY4OTQ1NywicGF0aCI6Ii8xODAwODQ1LzM3OTI2NTEwMy05N2MyOTA2Yy1lMmY3LTQxMmItODc1YS1lZjEwYjBkNmFlNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMTMxNzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYwM2UxM2JmMjQ5MzE0NzYxOTNkYWNiMTlmMzA4ZDAxNGZkYjA3YWU5NmM3OTMwYjdhZTc5YTNmN2VlYWYxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._ixT2uEudFx-2gOEBiGuU3gNXpJ0X2qye4uaeQGxdgs)

Ill come up with a more comprehensive solution as a follow up I don't think i can come up with a solution that would preserve the 1 acl rule mandatory to a client in a very short time

2024-10-23 15:01 UTC, joepavitt requested changes
Still have "Hello World" in the Empty State - otherwise, looking good.

2024-10-23 15:09 UTC, hardillb commented
fixed the empty state

![image](https://github.com/user-attachments/assets/e6d2f3a1-ac6d-4188-a18b-494b3d0a27cd)

2024-10-23 15:24 UTC, cstns commented
> fixed the empty state
> 
> ![image](https://private-user-images.githubusercontent.com/1800845/379335877-e6d2f3a1-ac6d-4188-a18b-494b3d0a27cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTY0ODgsIm5iZiI6MTcyOTY5NjE4OCwicGF0aCI6Ii8xODAwODQ1LzM3OTMzNTg3Ny1lNmQyZjNhMS1hYzZkLTQxODgtYTE4Yi00OTRiM2QwYTI3Y2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMTUwOTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU5OTQ5NDcwY2M3NzJhZTQ2YjBkNTI5YWRiODMzMTIwNTY0NzI4Y2VmN2JmYWY2YTI4MjBhZGQ5ZTdlMDc4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lo6w6PEanYuo_bZgo0KfH5oRQ0wgwcV2qI4vYNV_xMA)

Was just about to do so, spotted it whilst writing e2e tests. 

I took the liberty to make the logo smaller and add some accompanying text

2024-10-23 15:25 UTC, joepavitt commented on test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js
> +        // eslint-disable-next-line cypress/require-data-selectors
This shouldn't be needed as you _are_ using a `data` selector?

2024-10-23 15:27 UTC, joepavitt submitted a review, later dismissed

2024-10-23 15:27 UTC, joepavitt commented on test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js
>          cy.get('.ff-dialog-header').contains('Create Snapshot')
`data-el="create-client-dialog"` exists on the dialog, this should be included here as a selector

2024-10-23 15:27 UTC, joepavitt commented on test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js
>                  cy.get('main').contains('Create your First Snapshot')
```suggestion
                cy.get('div[data-el="empty-state"]').contains('Create your First Snapshot')
```

2024-10-23 15:27 UTC, joepavitt commented on test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js
> +        // eslint-disable-next-line cypress/require-data-selectors
and all of these, we should be using `data-` selectors, not classes

2024-10-23 15:28 UTC, cstns commented on test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js
>          cy.get('.ff-dialog-box button.ff-btn.ff-btn--primary').should('be.disabled')
this one doesn't have a data selector

2024-10-23 15:32 UTC, cstns commented on test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js
>          cy.get('.ff-dialog-box button.ff-btn.ff-btn--primary').should('be.disabled')
my local linter is failing after their removal

2024-10-23 16:41 UTC, cstns commented
I'll mark the e2e selector changes as resolved and take care of them on the follow up task

2024-10-23 16:52 UTC, cstns commented
created https://github.com/FlowFuse/flowfuse/issues/4685 as a follow up task. Feel free to add things that I may have missed

2024-10-23 18:53 UTC, cstns approved these changes

2024-10-24 07:45 UTC, merged