Add connection test button to LDAP SSO page
FlowFuse/flowfuse pull request #4787
Opened 2024-11-15 11:49 UTC by hardillb

fixes #4782

## Description

Adds ability to test SSO LDAP credentials

This adds 1 new API endpoint and a minor change to the LDAP SSO config page to add test button.

- POST `/ee/sso/providers/test` takes the same payload as the update provider, and needs same permissions

Returns 200 and empty json for success or 400 and standard error json for failure, with messages to suite the type of failure.

feedback is via Alerts, success

![image](https://github.com/user-attachments/assets/ab7d05cf-1a06-4294-a9a1-c3a310c47b02)

or for failure

![image](https://github.com/user-attachments/assets/bfedf140-d3e6-48a3-9d23-cab920bf31b3)

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-11-15 12:02 UTC, hardillb commented
Not sure how to test this without mocking a LDAP server.

The old `ldap` nodejs module that we deliberately didn't use has LDAP server support, so we could add it as a dev dependency to test this (and other bits of LDAP SSO)

2024-11-15 14:32 UTC, knolleary approved these changes

2024-11-15 14:33 UTC, knolleary commented
Agreed we aren't well setup for testing ldap in CI; lets not spend time on that right now.

2024-11-15 14:39 UTC, knolleary requested changes
Having approved initially, spotted the error reporting was mismatched in one scenario in terms of the property used to store the message. Have proposed changes to align them all. Also made the test button smaller.

2024-11-19 10:20 UTC, knolleary approved these changes

2024-11-19 10:20 UTC, merged