Remove notifications for deleted instances
FlowFuse/flowfuse pull request #4899
Opened 2024-12-09 16:59 UTC by hardillb

fixes #4845

## Description

Adds afterDestroy hook to Projects table remove Notifications when Instances are deleted.

Also includes a migration to remove orphaned Notifications.

## Related Issue(s)

 #4845

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [x] Includes a DB migration? -> add the `area:migration` label

2024-12-09 17:00 UTC, hardillb commented
We should probably do Devices as well, but want the approach verifying first

2024-12-10 09:38 UTC, knolleary commented
Can we look at doing a bulk delete sql rather than lots of individual ones?

https://sequelize.org/docs/v7/querying/delete/#deleting-in-bulk

2024-12-10 09:45 UTC, hardillb commented
I'll have another look, but we only have raw SQL access at this point (none of the models are loaded when the migrations run).

And the Notification table doesn't have a bare field with the project id that would could do a `WHERE "projectId" NOT IN (SELECT "id" from Projects)`

2024-12-10 09:47 UTC, knolleary commented
Good point; the reference field doesn't lend itself to using with `in`.

2024-12-13 10:12 UTC, knolleary requested changes
Issue with the count query across both support db flavours.

2024-12-13 10:12 UTC, knolleary commented on forge/db/migrations/20241209-01-remove-dead-instance-notifications.js
> +                    if (projectExits[0] === 0) {
Running this against sqlite and postgres results in different shapes of results that don't work with the test that is then performed on them

**sqlite**
```
[ [ { 'count(*)': 1 } ], Statement {} ]
```

**postgres**
```
[ [ { count: '1' } ], Result { ... } ] ]
```


In neither case will the current code correctly match the actual result. Note the different field names and the values are different types (int/string).

```suggestion
                    const projectQuery = `SELECT count(*) as c from "Projects" WHERE "id" = '${projectId}' LIMIT 1;`
                    const [[projectCount]] = await context.sequelize.query(projectQuery)
                    const count = parseInt(projectCount.c)
                    if (count === 0) {
```

2024-12-13 15:04 UTC, knolleary approved these changes

2024-12-13 15:05 UTC, merged