Allow for prefix/suffix to SSO GroupNames
FlowFuse/flowfuse pull request #4902
Opened 2024-12-11 14:01 UTC by hardillb

fixes #4768

## Description

Allows a prefix and suffix length to be defined for SSO group names, this works for both SAML and LDAP.

e.g.

ff requires groupnames in the following format `ff-teamslug-role`, this allows an arbitrary number of characters to be before and after this format. e.g.

with prefix and suffix length set to 5 the following group would match

`test_ff-teamslug-role_test`

![image](https://github.com/user-attachments/assets/e78de00b-3170-45f5-aa0e-e728eec77ba7)

## Related Issue(s)

#4768

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-12-11 14:01 UTC, hardillb commented
Needs a doc update

2024-12-11 15:52 UTC, hardillb commented
Tests for SAML pattern, the LDAP function needs a functional LDAP server to run against.

I did test both against my local KeyCloak and LDAP system

2024-12-13 10:31 UTC, knolleary commented on docs/admin/sso/ldap.md
> +
```suggestion
An optional prefix and suffix can be include in the group name to support LDAP providers that have existing naming policies. The SSO configuration can be configured with the lengths of these values so they will be stripped off before the group name is validated.

For example, if an organisation requires all groups to begin with `acme-org-`, a prefix length of `9` can be set and the group `acme-org-ff-development-owner` will be handled as `ff-development-owner`.
```

2024-12-13 10:32 UTC, knolleary commented on docs/admin/sso/saml.md
> +
```suggestion
An optional prefix and suffix can be include in the group name to support SAML providers that have existing naming policies. The SSO configuration can be configured with the lengths of these values so they will be stripped off before the group name is validated.

For example, if an organisation requires all groups to begin with `acme-org-`, a prefix length of `9` can be set and the group `acme-org-ff-development-owner` will be handled as `ff-development-owner`.
```

2024-12-13 10:35 UTC, knolleary commented on frontend/src/pages/admin/Settings/SSO/createEditProvider.vue
> +                            <template #description>The length of any prefix added to the FlowFuse Group Name format</template>
```suggestion
                            Group Name Prefix Length
                            <template #description>The length of any prefix added to the FlowFuse Group Name format</template>
```

2024-12-13 10:37 UTC, knolleary commented on test/unit/forge/ee/lib/sso/index_spec.js
> +                groupSuffixLength: 5
```suggestion
                    'test_ff-ateam-magician_err',
                    'test_ff-ateam-member_test2',
                    'test_ff-bteam-owner_test2',
                    'ff-ateam-admin_test'
                ]
            }, app.user, {
                groupAssertionName: 'ff-roles',
                groupAllTeams: true,
                groupPrefixLength: 5,
                groupSuffixLength: 6
```

Got itchy using the same value for both pre/suffix as it wouldn't spot any mix up in applying the wrong value to the wrong end.

2024-12-13 10:39 UTC, knolleary requested changes
Approved, but some doc/text/updates to apply first.

2024-12-13 13:49 UTC, knolleary approved these changes

2024-12-13 13:49 UTC, merged