Loading component displayed when loading data from API
FlowFuse/flowfuse pull request #656
Opened 2022-06-01 16:19 UTC by joepavitt

Closes #654

2022-06-06 15:00 UTC, knolleary commented on frontend/src/pages/team/Projects.vue
> +        <template v-else-if="!loading">
This condition needs moving to the top so it takes precedence over the others. As it stands, it is never being reached.

2022-06-06 15:06 UTC, knolleary commented on frontend/src/pages/team/Devices/index.vue
> +        <ff-loading v-else message="Loading Devices..." />
This condition needs moving to the top so it takes precedence over the others. As it stands, it is never being reached.

2022-06-06 15:07 UTC, knolleary requested changes
A couple instances where the `v-if` logic isn't being reached to display the loading component.

2022-06-07 10:13 UTC, knolleary requested changes

2022-06-07 10:13 UTC, knolleary commented on frontend/src/pages/team/Devices/index.vue
> +            loading: false,
We're missing the code to set `loading=true` when retrieving the list of devices

2022-06-07 12:24 UTC, joepavitt commented
@knolleary fixed the loading variable setting in devices accordingly.

2022-06-07 14:30 UTC, merged